allowBuilds:
  sharp: true
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - sharp
  - unrs-resolver
overrides:
  "postcss": "^8.5.21"
  "sharp": "^0.35.3"
updateConfig:
  ignoreDependencies:
    - "@types/node"
