import type { Metadata } from "next";
import "./globals.css";
import { PersonalInfo } from "@/components/personalInfo";
import { Bento } from "@/components/bento";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/icon.svg", type: "image/svg+xml" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container mx-auto">
        <div className="grid grid-cols-1 gap-8 p-16 lg:grid-cols-3">
          <PersonalInfo />
          <main className="space-y-8 lg:col-span-2">
            <Bento>
              <div className="flex items-center gap-2">
                <Image
                  src="/icon.svg"
                  alt="Vercel Logo"
                  width={60}
                  height={60}
                  priority
                />
                <div>
                  <h2>Personal blog showing development of languages.</h2>
                  <p>Current journey: React</p>
                </div>
              </div>
            </Bento>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
